// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANQWgKfB__vbyJF3BVXfZ8Y-OhHCSLEM4',
    appId: '1:834480827839:web:07c6e265f0481fe112050a',
    messagingSenderId: '834480827839',
    projectId: 'yahe-be261',
    authDomain: 'yahe-be261.firebaseapp.com',
    storageBucket: 'yahe-be261.firebasestorage.app',
    measurementId: 'G-THRT4E1QPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbbENHM9ABceYBPgV28Av1nG_6Rxwa5xU',
    appId: '1:834480827839:android:02b82e7ff1cff40812050a',
    messagingSenderId: '834480827839',
    projectId: 'yahe-be261',
    storageBucket: 'yahe-be261.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGdnA2sXNbBtNdkop6QjTM8yCFArrXUWE',
    appId: '1:834480827839:ios:cc95ac556eec54f112050a',
    messagingSenderId: '834480827839',
    projectId: 'yahe-be261',
    storageBucket: 'yahe-be261.firebasestorage.app',
    iosBundleId: 'jp.nozawataiki.yahe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGdnA2sXNbBtNdkop6QjTM8yCFArrXUWE',
    appId: '1:834480827839:ios:02855319369cd9e412050a',
    messagingSenderId: '834480827839',
    projectId: 'yahe-be261',
    storageBucket: 'yahe-be261.firebasestorage.app',
    iosBundleId: 'jp.nozawataiki.surf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANQWgKfB__vbyJF3BVXfZ8Y-OhHCSLEM4',
    appId: '1:834480827839:web:e9f0f6c362d5ca8612050a',
    messagingSenderId: '834480827839',
    projectId: 'yahe-be261',
    authDomain: 'yahe-be261.firebaseapp.com',
    storageBucket: 'yahe-be261.firebasestorage.app',
    measurementId: 'G-1SZ5RXQC2K',
  );
}
